# Generated by Django 3.1.12 on 2025-04-29 00:36

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_auto_20250429_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=djongo.models.fields.JSONField(),
        ),
    ]
